# Site settings
title: wikiReview
email:
description:
baseurl:
url: #https://wikireview.tech

# Build settings
markdown: kramdown
highliter: redcarpet
permalink: /:title/
# Directory settings
exclude: [Gemfile, Gemfile.lock, .gitignore, node_modules, package.json, gulpfile.js, assets/css/sass/, CNAME, Rakefile, LICENSE, README.md]

#Gems
gems: [jekyll-paginate, jekyll-sitemap]

#Gems settings
paginate: 2

tag_page_layout: tag_page
tag_page_dir: tag
