# Site settings
title: wikiReview
email:
description:
baseurl:
url: #https://wikireview.tech

# Build settings
markdown: kramdown
highliter: redcarpet
permalink: /:title
# permalink: /:title

# Directory settings
exclude: [Gemfile, Gemfile.lock, .gitignore, node_modules, package.json, gulpfile.js, assets/css/sass/, Rakefile, LICENSE, README.md]

#Gems
gems: [jekyll-paginate, jekyll-sitemap]

#Gems settings
paginate: 10
paginate_path: /page:num
tag_page_layout: tag-page
tag_page_dir: tag
